title: "Shock-EU"
description: "A 'cradle' to mount and integrate the Spark (and Arcs) into the Eurorack format."
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
